# Generated by Django 2.1.4 on 2018-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(default=2)),
                ('birth_date', models.DateField()),
                ('smoker', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'UserInfo',
            },
        ),
    ]
